#!/usr/bin/env python3
"""Build the ISA-size vs translator-coverage time series.

Emits one row per (date, isa) with the size of the ISA at that date and how many of
those instructions Remill lifts.  Two ISAs are covered:

  x86-64  ISA size = distinct XED iforms in XED-to-XML's committed instructions.xml,
          sampled at every commit that regenerated that file.
  a64     ISA size = distinct A64 encodings in the ASL decode tree generated by
          mra_tools from ARM's per-release A64 ISA XML, sampled at every release.

Every point is measured twice against Remill and BOTH results are emitted:

  primary    CONTEMPORANEOUS - the newest Remill commit that existed on the day the
             vendor published that spec release.  This is what the figure and the
             paper table use, because the claim being made is that a hand-written
             lifter cannot keep pace with a moving ISA: it lets Remill visibly do
             development (x86 1,800 -> 2,003) while the ISA outruns it.
  secondary  FIXED at the latest Remill checkout, in the *_fixed columns.  Kept as a
             sensitivity check; it is deliberately NOT what the figure shows, because
             drawing today's Remill against every past year hides the development.

The `remill_ref` / `remill_date` columns record which Remill commit anchors each
point, so the pairing is auditable.
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import importlib
import importlib.util

count_asl = importlib.import_module("count_asl_instructions")
count_xed = importlib.import_module("count_xed_instructions")
cov_a64 = importlib.import_module("calculate_remill_a64_coverage")


def _load_hyphenated(name: str, filename: str):
    """The x86 script's filename contains a hyphen, so it cannot be imported by name."""
    path = Path(__file__).resolve().parent / filename
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


cov_x86 = _load_hyphenated("remill_x86_coverage", "calculate_remill_x86-64_coverage.py")

REPO = Path(__file__).resolve().parents[1]

FIELDS = [
    "date",
    "isa",
    "source",
    "spec_version",
    "spec_date",
    "spec_ref",
    "isa_instruction_count",
    "remill_ref",
    "remill_date",
    "remill_covered_count",
    "coverage_pct",
    "remill_ref_fixed",
    "remill_date_fixed",
    "remill_covered_fixed",
    "coverage_pct_fixed",
    "is_change_point",
]


def git(repo: Path, *args: str) -> str:
    r = subprocess.run(["git", "-C", str(repo), *args], check=True,
                       capture_output=True, text=True)
    return r.stdout


def remill_commit_before(date: str) -> tuple[str, str]:
    repo = REPO / "external" / "remill"
    commit = git(repo, "rev-list", "-1", f"--before={date}", "HEAD").strip()
    if not commit:
        commit = git(repo, "rev-list", "--max-parents=0", "HEAD").strip().split()[0]
    cdate = git(repo, "log", "-1", "--format=%ad", "--date=short", commit).strip()
    return commit, cdate


class RemillTrees:
    """Materialises Remill checkouts on demand, for the contemporaneous pairing."""

    def __init__(self) -> None:
        self._dirs: dict[str, Path] = {}
        self._tmp = Path(tempfile.mkdtemp(prefix="remill-series-"))

    def path_for(self, commit: str) -> Path:
        if commit not in self._dirs:
            dest = self._tmp / commit[:12]
            subprocess.run(
                ["git", "-C", str(REPO / "external" / "remill"),
                 "worktree", "add", "-q", "--detach", str(dest), commit],
                check=True, capture_output=True, text=True,
            )
            self._dirs[commit] = dest
        return self._dirs[commit]

    def cleanup(self) -> None:
        for dest in self._dirs.values():
            subprocess.run(["git", "-C", str(REPO / "external" / "remill"),
                            "worktree", "remove", "--force", str(dest)],
                           check=False, capture_output=True)


def remill_head() -> tuple[str, str]:
    repo = REPO / "external" / "remill"
    return (git(repo, "rev-parse", "HEAD").strip(),
            git(repo, "log", "-1", "--format=%ad", "--date=short", "HEAD").strip())


def a64_arch_root(tree: Path) -> Path | None:
    for rel in ("lib/Arch/AArch64", "remill/Arch/AArch64"):
        p = tree / rel
        if (p / "Runtime" / "Instructions.cpp").is_file():
            return p
    return None


def x86_runtime(tree: Path) -> Path | None:
    for rel in ("lib/Arch/X86/Runtime/Instructions.cpp", "remill/Arch/X86/Runtime/Instructions.cpp"):
        p = tree / rel
        if p.is_file():
            return p
    return None


def build_a64(trees: RemillTrees, cxx: str) -> list[dict]:
    rows: list[dict] = []
    head_commit, head_date = remill_head()
    fixed_root = REPO / "external" / "remill" / "lib" / "Arch" / "AArch64"

    prev_count = None
    for release in count_asl.available_releases():
        variants = count_asl.extract_a64_variants(count_asl.resolve_decode_file(release))
        spec_date = f"{release}-01"

        commit, cdate = remill_commit_before(spec_date)
        root = a64_arch_root(trees.path_for(commit))
        if root is None:
            continue
        now = cov_a64.coverage_against(variants, root)
        fix = cov_a64.coverage_against(variants, fixed_root)

        rows.append({
            "date": spec_date,
            "isa": "a64",
            "source": "arm-mra",
            "spec_version": release,
            "spec_date": spec_date,
            "spec_ref": f"specs/a64/{release}",
            "isa_instruction_count": now["total_variants"],
            "remill_ref": commit[:12],
            "remill_date": cdate,
            "remill_covered_count": now["supported_variants"],
            "coverage_pct": round(now["coverage_percent"], 2),
            "remill_ref_fixed": head_commit[:12],
            "remill_date_fixed": head_date,
            "remill_covered_fixed": fix["supported_variants"],
            "coverage_pct_fixed": round(fix["coverage_percent"], 2),
            "is_change_point": int(prev_count != now["total_variants"]),
        })
        prev_count = now["total_variants"]
    return rows


def _x86_rows(points, trees: RemillTrees, cxx: str, source: str) -> list[dict]:
    """points: iterable of (date, spec_date, spec_version, spec_ref, iform_set)."""
    rows: list[dict] = []
    head_commit, head_date = remill_head()
    fixed_runtime = REPO / "external" / "remill" / "lib" / "Arch" / "X86" / "Runtime" / "Instructions.cpp"

    prev_count = None
    for date, spec_date, spec_version, spec_ref, iforms in points:
        rcommit, rdate = remill_commit_before(spec_date or date)
        runtime = x86_runtime(trees.path_for(rcommit))
        if runtime is None:
            continue
        now = cov_x86.coverage_against(iforms, runtime, cxx, False)
        fix = cov_x86.coverage_against(iforms, fixed_runtime, cxx, False)

        rows.append({
            "date": date,
            "isa": "x86-64",
            "source": source,
            "spec_version": spec_version,
            "spec_date": spec_date,
            "spec_ref": spec_ref,
            "isa_instruction_count": now["total_iforms"],
            "remill_ref": rcommit[:12],
            "remill_date": rdate,
            "remill_covered_count": now["supported_iforms"],
            "coverage_pct": round(now["coverage_percent"], 2),
            "remill_ref_fixed": head_commit[:12],
            "remill_date_fixed": head_date,
            "remill_covered_fixed": fix["supported_iforms"],
            "coverage_pct_fixed": round(fix["coverage_percent"], 2),
            "is_change_point": int(prev_count != now["total_iforms"]),
        })
        prev_count = now["total_iforms"]
    return rows


def build_x86_intel(trees: RemillTrees, cxx: str) -> list[dict]:
    """Primary x86 measure: Intel's own xed_iform_enum_t at dated upstream-XED anchors."""
    pts = [(r["intel_date"], r["intel_date"], r["xed_version"], r["xed_commit"][:12],
            count_xed.load_enum_iforms(r["label"]))
           for r in count_xed.x86_manifest()]
    return _x86_rows(pts, trees, cxx, "intel-xed-enum")


def build_x86(trees: RemillTrees, cxx: str) -> list[dict]:
    """Secondary x86 measure: the third-party XED-to-XML export."""
    pts = []
    for commit, date in count_xed.instructions_xml_history():
        pts.append((date,
                    count_xed.xed_datafiles_date(commit) or "",
                    count_xed.xed_version_at_commit(commit) or "",
                    commit[:12],
                    count_xed.load_iforms_at_commit(commit)))
    return _x86_rows(pts, trees, cxx, "xed-to-xml-export")


ANNUAL_YEARS = range(2019, 2026)


def downsample_annual(rows: list[dict]) -> list[dict]:
    """One point per (source, isa, calendar year): the LAST release of that year.

    The same rule is applied to both ISAs so the grid is matched and reproducible.
    Years with no obtainable release are simply absent - nothing is interpolated.

    The grid starts at 2019 because that is where the data starts, for both ISAs at
    once: ARM's first machine-readable architecture specification is 2017-04 (Armv8.2-A)
    and its 2017-04..2019-09 releases are no longer served anywhere, so 2019-12 is the
    earliest A64 release obtainable; nothing before 2017-04 exists to measure.
    """
    best: dict[tuple, dict] = {}
    for r in rows:
        year = int(r["spec_date"][:4]) if r["spec_date"] else int(r["date"][:4])
        if year not in ANNUAL_YEARS:
            continue
        key = (r["source"], r["isa"], year)
        cur = best.get(key)
        if cur is None or (r["spec_date"] or r["date"]) >= (cur["spec_date"] or cur["date"]):
            best[key] = r
    out = [dict(best[k], year=k[2]) for k in sorted(best, key=lambda k: (k[1], k[0], k[2]))]
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--isa", choices=("x86-64", "a64", "both"), default="both")
    ap.add_argument("--cxx", default="c++")
    ap.add_argument("--out-csv", default="data/series.csv")
    ap.add_argument("--out-json", default="data/series.json")
    ap.add_argument("--out-annual", default="data/series_annual.csv",
                    help="Downsampled presentation grid: last release of each year, 2019-2025.")
    args = ap.parse_args()

    trees = RemillTrees()
    try:
        rows: list[dict] = []
        if args.isa in ("a64", "both"):
            rows += build_a64(trees, args.cxx)
        if args.isa in ("x86-64", "both"):
            rows += build_x86_intel(trees, args.cxx)
            rows += build_x86(trees, args.cxx)
    finally:
        trees.cleanup()

    rows.sort(key=lambda r: (r["isa"], r["source"], r["date"]))

    csv_path = REPO / args.out_csv
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows)

    json_path = REPO / args.out_json
    json_path.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")

    annual = downsample_annual(rows)
    ann_path = REPO / args.out_annual
    with ann_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["year"] + FIELDS)
        w.writeheader()
        w.writerows(annual)

    for r in rows:
        print(f"{r['date']}  {r['isa']:<7} {r['source']:<18} {r['isa_instruction_count']:>6} instrs  "
              f"{r['remill_covered_count']:>5} covered ({r['remill_ref']} {r['remill_date']})  "
              f"{r['coverage_pct']:>6.2f}%")
    print(f"\nwrote {csv_path}, {json_path} and {ann_path} "
          f"({len(rows)} rows, {len(annual)} annual; remill contemporaneous "
          f"primary, fixed-at-latest in the *_fixed columns)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
