#!/usr/bin/env python3
"""Build the ISA-size vs translator-coverage time series.

Emits one row per (date, isa) with the size of the ISA at that date and how many of
those instructions Remill lifts.  Two ISAs are covered:

  x86-64  ISA size = distinct XED iforms in XED-to-XML's committed instructions.xml,
          sampled at every commit that regenerated that file.
  a64     ISA size = distinct A64 encodings in the ASL decode tree generated by
          mra_tools from ARM's per-release A64 ISA XML, sampled at every release.

Remill is held FIXED at the latest checkout by default (`--remill fixed`), so the
series answers "the target moved".  `--remill contemporaneous` instead measures the
Remill that existed at each date, answering "could a hand-written lifter keep up".
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import importlib
import importlib.util

count_asl = importlib.import_module("count_asl_instructions")
count_xed = importlib.import_module("count_xed_instructions")
cov_a64 = importlib.import_module("calculate_remill_a64_coverage")


def _load_hyphenated(name: str, filename: str):
    """The x86 script's filename contains a hyphen, so it cannot be imported by name."""
    path = Path(__file__).resolve().parent / filename
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


cov_x86 = _load_hyphenated("remill_x86_coverage", "calculate_remill_x86-64_coverage.py")

REPO = Path(__file__).resolve().parents[1]

FIELDS = [
    "date",
    "isa",
    "spec_version",
    "spec_date",
    "spec_ref",
    "isa_instruction_count",
    "remill_ref",
    "remill_date",
    "remill_covered_count",
    "coverage_pct",
    "is_change_point",
]


def git(repo: Path, *args: str) -> str:
    r = subprocess.run(["git", "-C", str(repo), *args], check=True,
                       capture_output=True, text=True)
    return r.stdout


def remill_commit_before(date: str) -> tuple[str, str]:
    repo = REPO / "external" / "remill"
    commit = git(repo, "rev-list", "-1", f"--before={date}", "HEAD").strip()
    if not commit:
        commit = git(repo, "rev-list", "--max-parents=0", "HEAD").strip().split()[0]
    cdate = git(repo, "log", "-1", "--format=%ad", "--date=short", commit).strip()
    return commit, cdate


class RemillTrees:
    """Materialises Remill checkouts on demand (for --remill contemporaneous)."""

    def __init__(self) -> None:
        self._dirs: dict[str, Path] = {}
        self._tmp = Path(tempfile.mkdtemp(prefix="remill-series-"))

    def path_for(self, commit: str) -> Path:
        if commit not in self._dirs:
            dest = self._tmp / commit[:12]
            subprocess.run(
                ["git", "-C", str(REPO / "external" / "remill"),
                 "worktree", "add", "-q", "--detach", str(dest), commit],
                check=True, capture_output=True, text=True,
            )
            self._dirs[commit] = dest
        return self._dirs[commit]

    def cleanup(self) -> None:
        for dest in self._dirs.values():
            subprocess.run(["git", "-C", str(REPO / "external" / "remill"),
                            "worktree", "remove", "--force", str(dest)],
                           check=False, capture_output=True)


def a64_arch_root(tree: Path) -> Path | None:
    for rel in ("lib/Arch/AArch64", "remill/Arch/AArch64"):
        p = tree / rel
        if (p / "Runtime" / "Instructions.cpp").is_file():
            return p
    return None


def x86_runtime(tree: Path) -> Path | None:
    for rel in ("lib/Arch/X86/Runtime/Instructions.cpp", "remill/Arch/X86/Runtime/Instructions.cpp"):
        p = tree / rel
        if p.is_file():
            return p
    return None


def build_a64(mode: str, trees: RemillTrees, cxx: str) -> list[dict]:
    rows: list[dict] = []
    default_root = REPO / "external" / "remill" / "lib" / "Arch" / "AArch64"
    head_commit = git(REPO / "external" / "remill", "rev-parse", "HEAD").strip()
    head_date = git(REPO / "external" / "remill", "log", "-1", "--format=%ad",
                    "--date=short", "HEAD").strip()

    prev_count = None
    for release in count_asl.available_releases():
        variants = count_asl.extract_a64_variants(count_asl.resolve_decode_file(release))
        if mode == "contemporaneous":
            commit, cdate = remill_commit_before(f"{release}-28")
            root = a64_arch_root(trees.path_for(commit))
            if root is None:
                continue
        else:
            commit, cdate, root = head_commit, head_date, default_root

        s = cov_a64.coverage_against(variants, root)
        rows.append({
            "date": f"{release}-01",
            "isa": "a64",
            "spec_version": release,
            "spec_date": f"{release}-01",
            "spec_ref": f"specs/a64/{release}",
            "isa_instruction_count": s["total_variants"],
            "remill_ref": commit[:12],
            "remill_date": cdate,
            "remill_covered_count": s["supported_variants"],
            "coverage_pct": round(s["coverage_percent"], 2),
            "is_change_point": int(prev_count != s["total_variants"]),
        })
        prev_count = s["total_variants"]
    return rows


def build_x86(mode: str, trees: RemillTrees, cxx: str) -> list[dict]:
    rows: list[dict] = []
    default_runtime = REPO / "external" / "remill" / "lib" / "Arch" / "X86" / "Runtime" / "Instructions.cpp"
    head_commit = git(REPO / "external" / "remill", "rev-parse", "HEAD").strip()
    head_date = git(REPO / "external" / "remill", "log", "-1", "--format=%ad",
                    "--date=short", "HEAD").strip()

    prev_count = None
    for commit, date in count_xed.instructions_xml_history():
        iforms = count_xed.load_iforms_at_commit(commit)
        if mode == "contemporaneous":
            rcommit, rdate = remill_commit_before(date)
            runtime = x86_runtime(trees.path_for(rcommit))
            if runtime is None:
                continue
        else:
            rcommit, rdate, runtime = head_commit, head_date, default_runtime

        s = cov_x86.coverage_against(iforms, runtime, cxx, False)
        xed_version = count_xed.xed_version_at_commit(commit) or ""
        rows.append({
            "date": date,
            "isa": "x86-64",
            "spec_version": xed_version,
            "spec_date": count_xed.xed_datafiles_date(commit) or "",
            "spec_ref": commit[:12],
            "isa_instruction_count": s["total_iforms"],
            "remill_ref": rcommit[:12],
            "remill_date": rdate,
            "remill_covered_count": s["supported_iforms"],
            "coverage_pct": round(s["coverage_percent"], 2),
            "is_change_point": int(prev_count != s["total_iforms"]),
        })
        prev_count = s["total_iforms"]
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--isa", choices=("x86-64", "a64", "both"), default="both")
    ap.add_argument("--remill", choices=("fixed", "contemporaneous"), default="fixed",
                    help="fixed: latest Remill for every point (default). "
                         "contemporaneous: the Remill that existed at each date.")
    ap.add_argument("--cxx", default="c++")
    ap.add_argument("--out-csv", default="data/series.csv")
    ap.add_argument("--out-json", default="data/series.json")
    args = ap.parse_args()

    trees = RemillTrees()
    try:
        rows: list[dict] = []
        if args.isa in ("a64", "both"):
            rows += build_a64(args.remill, trees, args.cxx)
        if args.isa in ("x86-64", "both"):
            rows += build_x86(args.remill, trees, args.cxx)
    finally:
        trees.cleanup()

    rows.sort(key=lambda r: (r["isa"], r["date"]))

    csv_path = REPO / args.out_csv
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows)

    json_path = REPO / args.out_json
    json_path.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")

    for r in rows:
        print(f"{r['date']}  {r['isa']:<7} {r['isa_instruction_count']:>6} instrs  "
              f"{r['remill_covered_count']:>5} covered  {r['coverage_pct']:>6.2f}%")
    print(f"\nwrote {csv_path} and {json_path} ({len(rows)} rows, remill={args.remill})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
