#!/usr/bin/env python3
"""Count unique A64 instruction variants in mra_tools-generated ASL decode files.

A "variant" is one `__encoding <name> // <VARIANT>` entry inside the `__decode A64`
section, i.e. one named encoding of the A64 instruction set.  The same definition is
used for every snapshot in the time series, so counts are comparable across releases.
"""

from __future__ import annotations

import argparse
import gzip
import re
from pathlib import Path


ENCODING_COMMENT_RE = re.compile(r"=>\s+__encoding\s+\S+\s+//\s+([A-Za-z0-9_]+)\s*$")

# The two anchor snapshots the study started from.  Kept so the historical numbers
# (2336 / 4331) stay reproducible verbatim.
SNAPSHOT_DECODE_FILES = {
    "2020-03": Path("external/arch8.6/arch_decode.asl"),
    "2026": Path("external/arch9.7/arch_decode.asl"),
}

# Per-release decode files generated by scripts/fetch_a64_specs.sh.
SPEC_DIR = Path("specs/a64")


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _open_text(path: Path):
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8")
    return path.open("r", encoding="utf-8")


def extract_a64_variants(path: Path) -> set[str]:
    variants: set[str] = set()
    in_a64 = False

    with _open_text(path) as handle:
        for raw_line in handle:
            line = raw_line.rstrip("\n")

            if line.startswith("__decode "):
                in_a64 = line == "__decode A64"
                continue

            if not in_a64:
                continue

            match = ENCODING_COMMENT_RE.search(line)
            if match:
                variants.add(match.group(1))

    return variants


def load_a64_variants(snapshot_name: str) -> set[str]:
    return extract_a64_variants(SNAPSHOT_DECODE_FILES[snapshot_name])


def resolve_decode_file(release: str) -> Path:
    """Path to the decode file for an ARM release label such as '2021-09'."""
    base = repo_root() / SPEC_DIR / release
    for candidate in (base / "arch_decode.asl.gz", base / "arch_decode.asl"):
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"no decode file for release {release} under {base}")


def available_releases() -> list[str]:
    """ARM release labels (YYYY-MM) that have a generated decode file, oldest first."""
    root = repo_root() / SPEC_DIR
    if not root.is_dir():
        return []
    out = []
    for child in sorted(root.iterdir()):
        if child.is_dir() and re.fullmatch(r"\d{4}-\d{2}", child.name):
            if (child / "arch_decode.asl.gz").is_file() or (child / "arch_decode.asl").is_file():
                out.append(child.name)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Count unique A64 instruction variants from generated ASL decode files."
    )
    parser.add_argument(
        "--decode-file",
        action="append",
        dest="decode_files",
        help="Path to an arch_decode.asl(.gz) file. Defaults to external/arch8.6 and external/arch9.7.",
    )
    parser.add_argument(
        "--release",
        action="append",
        dest="releases",
        help="ARM release label (YYYY-MM) from specs/a64/. May be repeated.",
    )
    parser.add_argument(
        "--all-releases",
        action="store_true",
        help="Count every release found under specs/a64/.",
    )
    parser.add_argument(
        "--emit-names",
        action="store_true",
        help="Print the sorted variant names for each decode file.",
    )
    args = parser.parse_args()

    if args.all_releases:
        decode_files = [resolve_decode_file(r) for r in available_releases()]
    elif args.releases:
        decode_files = [resolve_decode_file(r) for r in args.releases]
    elif args.decode_files:
        decode_files = [Path(p) for p in args.decode_files]
    else:
        decode_files = list(SNAPSHOT_DECODE_FILES.values())

    for path in decode_files:
        variants = extract_a64_variants(path)
        print(f"{path}: {len(variants)} unique A64 instruction variants")
        if args.emit_names:
            for name in sorted(variants):
                print(name)
            print()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
